language: cpp

compiler:
  - clang
  - gcc
env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - echo "yes" | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get purge libboost*1.46*
  - sudo apt-cache policy libboost-dev
  - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev
  - sudo apt-get install -qq libzmq3-dev
  - sudo pip install cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIG -DRemus_NO_SYSTEM_BOOST:BOOL=OFF -DRemus_ENABLE_COVERAGE:BOOL=ON ..
  - ctest -D ExperimentalUpdate -D Experimental -j6 --schedule-random --track Travis
  - echo ${TRAVIS_PULL_REQUEST}
  - echo ${TRAVIS_COMMIT}

after_success:
  - cd ..
  - coveralls --root . --build ./build --exclude ./thirdparty --exclude ./examples --exclude-pattern '\./build/.*\.c(?:xx)?' --exclude-pattern '\./build/.*\.h(?:xx)?'

notifications:
  email:
    - robert.maynard@kitware.com
  on_success: change
  on_failure: always
