language: cpp

compiler:
  - clang
  - gcc
env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - echo "yes" | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get purge libboost*1.46*
  - sudo apt-cache policy libboost-dev
  - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev
  - sudo apt-get install -qq libzmq3-dev
  - sudo pip install cpp-coveralls
  - sudo apt-get install curl


script:
  - mkdir build
  - cd build
  - ctest -D ExperimentalUpdate
  - sudo python ./../build.py
  - ctest -D Experimental -j6 --schedule-random --track Travis
  - curl http://142.105.147.205/Remus/pullRequest/robertmaynard/Remus/${TRAVIS_PULL_REQUEST}/${TRAVIS_COMMIT}


after_success:
  - cd ..
  - coveralls --root . --build ./build --exclude ./thirdparty --exclude ./examples --exclude-pattern '\./build/.*\.c(?:xx)?' --exclude-pattern '\./build/.*\.h(?:xx)?'

notifications:
  email:
    - robert.maynard@kitware.com
  on_success: change
  on_failure: always
